version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2
    steps:
      - checkout:
          path: ~/Price_increase
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:3.0.2
      - image: circleci/mysql:8.0.29
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: price_increase_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    steps:
      - checkout:
          path:  ~/Price_increase
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rake db:schema:load

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
