version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2
    steps:
      - checkout
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:3.0.2
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: price_increase_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      RAILS_ENV: test
    steps:
      - setup
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load 
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
