version: 2.1
jobs:
  build:
    working_directory: ~/Price_increase
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout:
          path: ~/Price_increase
      - run:
          name: Linuxbrew のインストールと設定
          command: |
          sudo apt-get install build-essential curl file git
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"      echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:$PATH"' >> $BASH_ENV      echo 'export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"' >> $BASH_ENV      echo 'export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"' >> $BASH_ENV
      - run:
          name: bundle installの実行
          command: |
            brew install imagemagick@6
            bundle install

  test:
    docker:
      - image: cimg/ruby:3.0.2
      - image: circleci/mysql:8.0.29
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: Price_increase_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/Price_increase
    steps:
      - checkout:
          path:  ~/Price_increase
      - run:
          name: Linuxbrew のインストールと設定
          command: |
          sudo apt-get install build-essential curl file git
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"      echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:$PATH"' >> $BASH_ENV      echo 'export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"' >> $BASH_ENV      echo 'export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"' >> $BASH_ENV
      - run:
          name: bundle installの実行
          command: |
            brew install imagemagick@6
            bundle install
      - run:
          name: Database setup
          command: bundle exec rake db:schema:load

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
